services:
  app:
    build:
     context: .
     dockerfile: Dockerfile
     network: host
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./zrconfig.py:/zwiftrunalyze/zrconfig.py
      - ./logs/:/zwiftrunalyze/logs

