services:
  app:
    build:
     context: .
     dockerfile: Dockerfile
     network: host
    #network_mode: host 
    ports:
      - 5001:5000
    volumes:
      - ./data/:/zwiftrunalyze/data
      - ./zrconfig.py:/zwiftrunalyze/zrconfig.py

