version: '3.7'

services:
  app:
    build:
     context: .
     dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./data/:/zwiftrunalyze/data
      - ./zrconfig.py:/zwiftrunalyze/zrconfig.py

